repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0  # Ensure this is the latest stable version
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
